services:
  grafana:
    user: root
    container_name: 'grafana-tachyontsdb-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-11.3.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/tachyontsdb-tachyondb-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/tachyontsdb-tachyondb-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.tachyontsdb-tachyondb-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: tachyontsdb-tachyondb-datasource
